import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from "next/font/local";
//import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

const pretendard = localFont({
  src: "../static/fonts/PretendardVariable.woff2",
  display: "swap",
  variable: '--font-pretendard',
  // ..
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full overflow-hidden`}>
      <body className={`${pretendard.className} h-full `}>
          {children}       
      </body>
    </html>
  )
}
  